version: "3.4"
services:
  jupyter:
    image: 127.0.0.1:5001/gpu-jupyter
    build: ./src/
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/work
      - ./jupyter:/home/jovyan/.jupyter
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    # enable sudo permissions
    user:
      "root"
